name: Deploy rustdoc to Pages

on:
  workflow_dispatch:
  push:
    branches: ["rust"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set up Rust
        run: |
          rustup toolchain install --profile minimal --no-self-update stable
          rustup default stable
      - uses: Swatinem/rust-cache@v2

      - run: |
          cargo doc --no-deps
          mkdir pages
          cp -R target/doc/* pages/

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: pages
      - id: deployment
        uses: actions/deploy-pages@v4
