name: Rust tests

on:
  push:
    branches:
      - main
      - rust
  pull_request:

env:
  RUSTFLAGS: -Dwarnings
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  build_and_test:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
          - windows

    runs-on: ${{ matrix.os }}-latest
    name: Build and test on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Set up Rust
      run: |
        rustup toolchain install --profile minimal --no-self-update stable
        rustup default stable
    - uses: Swatinem/rust-cache@v2

    - run: cargo check --all
    - run: cargo test --all

  check_fmt_and_docs:
    name: Checking fmt and docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Set up Rust
      run: |
        rustup toolchain install --profile minimal --no-self-update stable --component rustfmt,clippy
        rustup default stable
    - uses: Swatinem/rust-cache@v2

    - run: cargo fmt --all -- --check
    - run: cargo doc --no-deps
