name: Source Package

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Run build & test
      run: |
        cd sourcepkg
        make check
